# -*- coding: utf-8 -*-
"""juego.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6p0HJBUux-4LTLXjwKEKGzxivmSwsNE
"""

import random

def elegir_dificultad():
    print("Selecciona un nivel de dificultad:")
    print("1 - Fácil (número entre 1 y 50, 10 intentos)")
    print("2 - Medio (número entre 1 y 100, 7 intentos)")
    print("3 - Difícil (número entre 1 y 200, 5 intentos)")

    while True:
        opcion = input("Ingresa 1, 2 o 3: ")
        if opcion == '1':
            return (1, 50, 10)
        elif opcion == '2':
            return (1, 100, 7)
        elif opcion == '3':
            return (1, 200, 5)
        else:
            print("Opción inválida. Intenta de nuevo.")

def jugar():
    print("¡Bienvenido al juego de Adivina el Número!")

    minimo, maximo, intentos_maximos = elegir_dificultad()
    numero_secreto = random.randint(minimo, maximo)
    intentos_realizados = 0

    print(f"\nHe pensado en un número entre {minimo} y {maximo}. ¡Adivina cuál es!")
    print(f"Tienes {intentos_maximos} intentos.\n")

    while intentos_realizados < intentos_maximos:
        try:
            intento = int(input(f"Intento #{intentos_realizados + 1}: "))
            intentos_realizados += 1

            if intento < numero_secreto:
                print("Muy bajo.")
            elif intento > numero_secreto:
                print("Muy alto.")
            else:
                print(f"¡Correcto! Adivinaste el número en {intentos_realizados} intentos.")
                return
        except ValueError:
            print("Por favor, ingresa un número válido.")

    print(f"\nLo siento, has agotado tus intentos. El número era: {numero_secreto}")

# Ejecutar el juego
jugar()